// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByw_grODHcIb8mn3ILMCKetVhHAC3qPh8',
    appId: '1:313676958052:web:358e6dd5fb688a61001271',
    messagingSenderId: '313676958052',
    projectId: 'chat-analytics-b96ea',
    authDomain: 'chat-analytics-b96ea.firebaseapp.com',
    storageBucket: 'chat-analytics-b96ea.appspot.com',
    measurementId: 'G-PC63W0ECDD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAl-UEDRkc8VlU9ci-sB5Wh2VqFgbHLN0E',
    appId: '1:313676958052:android:d97ffea901e3c5cc001271',
    messagingSenderId: '313676958052',
    projectId: 'chat-analytics-b96ea',
    storageBucket: 'chat-analytics-b96ea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYlwQCwsIkJzJvXq3lKZxVRUKfzIdKd5g',
    appId: '1:313676958052:ios:6b717a2cf07185a7001271',
    messagingSenderId: '313676958052',
    projectId: 'chat-analytics-b96ea',
    storageBucket: 'chat-analytics-b96ea.appspot.com',
    androidClientId: '313676958052-e3p970v2h8et6ov1veoh6t99raa5ip4s.apps.googleusercontent.com',
    iosClientId: '313676958052-66hf4i8pv3s8dl5hcjjfemjv7gun93pv.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatAnalytics',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYlwQCwsIkJzJvXq3lKZxVRUKfzIdKd5g',
    appId: '1:313676958052:ios:22a35456ed82af64001271',
    messagingSenderId: '313676958052',
    projectId: 'chat-analytics-b96ea',
    storageBucket: 'chat-analytics-b96ea.appspot.com',
    androidClientId: '313676958052-e3p970v2h8et6ov1veoh6t99raa5ip4s.apps.googleusercontent.com',
    iosClientId: '313676958052-qa4srrh6imemjmg0gn35opicuc04dbqv.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatAnalytics.RunnerTests',
  );
}
